### ISSUE TITLE
Helper script to map UI navigation.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ryanmcnz/gmweb#4]
Such as ```Tab```, ```Up```, ```Down```, ```Left```, ```Right```, ```Space```, ```Enter```, ```Esc``` etc.

Could be used in GM to map those operations to gamepad for switching between input fields or buttons.

**Comment by ryanmcnz** [comment]
There's web libraries to do this one as well, similar to how there's InputDog for GameMaker (which has a helper script for mapping certain actions across keys/buttons/clicks/etc).
