### ISSUE TITLE
Support for onScreen keyboard?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ryanmcnz/gmweb#5]
There probably is no way to call a mobile one given the age of the framework.
So one may need to be made if textual input is wanted via GamePad / Non Keyboard devices.

Alternatively one could just design games that do not require textual input.

**Comment by ryanmcnz** [comment]
Yeah this one is probably just one of those things that people would add to their game if need be, or would find an existing web library that does it. Not sure if that's something GMWeb would benefit from having built-in.
